stages:
    - checks
    - test
    - deploy

pre-commit:
    stage: checks
    image: python:3.10-bookworm
    variables:
        PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
    cache:
        paths:
            - ${PRE_COMMIT_HOME}
    script:
        - pip install pre-commit
        - pre-commit run --all-files

.tox_setup:
    before_script:
        - apt-get update
        - apt-get install redis-server -y
        - redis-server --daemonize yes
        - python -V
        - pip install tox
        - cd utils-test-app

check-docs:
    stage: checks
    extends: .tox_setup
    image: python:3.10-bookworm
    script:
        - tox -e docs

test-py310-dj42:
    extends: .tox_setup
    image: python:3.10-bookworm
    script:
        - tox -e py310-django42
        - bash <(curl -s https://codecov.io/bash)

test-py311-dj42:
    extends: .tox_setup
    image: python:3.11-bookworm
    script:
        - tox -e py311-django42
        - bash <(curl -s https://codecov.io/bash)

test-py312-dj42:
    extends: .tox_setup
    image: python:3.12-bookworm
    script:
        - tox -e py312-django42
        - bash <(curl -s https://codecov.io/bash)

test-py313-dj42:
    extends: .tox_setup
    image: python:3.13-bookworm
    script:
        - tox -e py313-django42
        - bash <(curl -s https://codecov.io/bash)

deploy-pypi:
    stage: deploy
    image: python:3.10-bookworm
    before_script:
        - pip install -U pip twine wheel build
    script:
        - python -m build
        - twine upload dist/*
    only:
        - tags
