[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "utils-test-app"
version = "0.2.0"
description = "tbd"
readme = "README.md"
requires-python = ">=3.8"
authors = [{ name = "Erik Kalkoken", email = "kalkoken87@gmail.com" }]
dependencies = ["requests"]

[project.optional-dependencies]
test = ["coverage", "factory_boy", "requests_mock"]

[project.urls]
Homepage = "https://gitlab.com/ErikKalkoken/allianceauth-app-utils"

[tool.flit.module]
name = "utils_test_app"

[tool.isort]
profile = "black"
multi_line_output = 3
sections = [
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    "DJANGO",
    "ALLIANCEAUTH",
    "FIRSTPARTY",
    "LOCALFOLDER",
]
known_allianceauth = ["allianceauth", "app_utils"]
known_django = ["django", "django_webtest", "esi", "eveuniverse"]
