[flake8]
exclude = .git, *migrations*
max-line-length = 88
select = C,E,F,W,B,B950
ignore = E203, E231, E501, W503, W291, W293


[tox]
envlist = {py37, py38, py39}-django{32}, {py38, py39, py310}-django{40}, docs

[testenv]
setenv =
    django32: DJANGO_SETTINGS_MODULE = testauth.settings_aa2
    django40: DJANGO_SETTINGS_MODULE = testauth.settings_aa3

deps=
    django32: allianceauth>=2.9,<3
    django40: allianceauth>=3,<4
    requests-mock
    coverage

commands=
    pip install -e ../../allianceauth-app-utils
    coverage run runtests.py -v 2
    coverage xml
    coverage report -m

[testenv:docs]
description = invoke sphinx-build to build the HTML docs
basepython = python3.8
deps = -r{toxinidir}/../docs/requirements.txt
commands =
    pip install -e ../../allianceauth-app-utils --no-deps
    sphinx-build -d "{toxworkdir}/docs_doctree" ../docs "{toxworkdir}/docs_out" --color -W -bhtml {posargs}
