[flake8]
exclude = .git, *migrations*
max-line-length = 88
select = C,E,F,W,B,B950
ignore = E203, E231, E501, W503, W291, W293

[tox]
envlist = {py38, py39, py310, py311, py312}-django{42, 52}, docs, pylint

[testenv]
setenv =
    django42: DJANGO_SETTINGS_MODULE = testauth.settings_aa4.local
    django52: DJANGO_SETTINGS_MODULE = testauth.settings_aa5.local

deps=
    django42: allianceauth>=4,<5
    django52: allianceauth>=5,<6

extras =
    test

commands_pre=
    pip list

commands=
    pip install -e ../../allianceauth-app-utils
    coverage run runtests.py -v 2
    coverage xml
    coverage report -m

[testenv:docs]
description = invoke sphinx-build to build the HTML docs
deps = -r{toxinidir}/../docs/requirements.txt
commands =
    pip install -e ../../allianceauth-app-utils --no-deps
    sphinx-build -d "{toxworkdir}/docs_doctree" ../docs "{toxworkdir}/docs_out" --color -W -bhtml {posargs}

[testenv:pylint]
deps=
    pylint
    pylint-django

commands=
    pip install -e ../../allianceauth-app-utils
    pylint --load-plugins pylint_django app_utils
